vm.swappiness=10
vm.vfs_cache_pressure=50

# Hardening reseau (audit 2026-05-02)
net.ipv4.conf.default.accept_source_route=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.default.send_redirects=0
net.ipv4.conf.all.log_martians=1
net.ipv4.conf.default.log_martians=1
