[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 5
banaction = ufw
allowipv6 = auto

[sshd]
enabled  = true
port     = ssh
logpath  = %(sshd_log)s
backend  = systemd
maxretry = 4
bantime  = 24h

[caddy-bad-requests]
enabled  = true
port     = http,https
logpath  = /var/log/caddy/relay-access.log
filter   = caddy-bad-requests
maxretry = 10
findtime = 2m
bantime  = 1h

[recidive]
enabled  = true
bantime  = 1w
findtime = 1d
maxretry = 3
backend  = systemd
filter   = recidive
