[Definition]
# Détecte dans les logs JSON de Caddy les codes d'erreur suspects et scans de paths
failregex = ^.*"remote_ip":"<HOST>".*"status":(?:400|401|403|405|408|429|444).*$
            ^.*"remote_ip":"<HOST>".*"uri":"(?:.*\.php|.*wp-|.*\.env|.*\.git|.*xmlrpc).*$

ignoreregex =
datepattern = {^LN-BEG}
